### ISSUE TITLE
Certificates not renewing

### ISSUE THREAD

**Issue by maxguru** [dodrio/docker-acme.sh#3]
I found a problem with the cron setup.  I'm not yet sure exactly what is causing this.

Apparently some settings are ignored.

```
/var/spool/cron/crontabs/root:5 0 * * * "/acme.sh"/acme.sh --cron --home "/acme.
sh" > /dev/null
```

Running the cron command directly seems to work, however, it doesn't renew anything.

Apparently, the CERT_HOME setting in /acme.sh/account.conf file is ignored.

When I tried running the following,
```
# "/acme.sh"/acme.sh --cron --home "/acme.sh" --cert-home ${CERT_DIR} --accountkey ${ACCOUNT_DIR}/account.key
```
it started to work.

Any ideas?

**Comment by m31271n** [comment]
I enconutered it before.  How about `"/acme.sh"/acme.sh --cron` in your box?

**Comment by m31271n** [comment]
And, maybe it's time to update according https://github.com/Neilpang/acme.sh/wiki/Run-acme.sh-in-docker

**Comment by maxguru** [comment]
`"/acme.sh"/acme.sh --cron` seems to work.
